export const SET_CREATE_TASK_DIALOG = 'SET_CREATE_TASK_DIALOG'
export const GET_TASKS = 'GET_TASKS'
export const CREATE_OR_UPDATE_TASK = 'CREATE_OR_UPDATE_TASK'
export const SET_SNACKBAR = 'SET_SNACKBAR'